package com.oasis.game;

import java.util.Random;
import java.util.Scanner;

public class NumberGuessingGame {

    public static void main(String[] args) {
    	 Scanner sc = new Scanner(System.in);
         Random random = new Random();
         char playAgain;
         int round = 1;
         String scoreSummary = "";
         do {

         System.out.println("======================================");
         System.out.println("      NUMBER GUESSING GAME");
         System.out.println("======================================");
         System.out.println("Guess the number generated by the computer!");
         System.out.println("Choose Difficulty Level:");
         System.out.println("1. Easy (1-50, 10 Attempts)");
         System.out.println("2. Medium (1-100, 7 Attempts)");
         System.out.println("3. Hard (1-200, 5 Attempts)");

         System.out.print("\nEnter your choice: ");
         int choice = sc.nextInt();

         int maxNumber = 100;
         int maxAttempts = 7;

         switch (choice) {
             case 1:
                 maxNumber = 50;
                 maxAttempts = 10;
                 break;

             case 2:
                 maxNumber = 100;
                 maxAttempts = 7;
                 break;

             case 3:
                 maxNumber = 200;
                 maxAttempts = 5;
                 break;

             default:
                 System.out.println("Invalid choice! Medium level selected.");
         }
         int randomNumber = random.nextInt(maxNumber) + 1;
         int attempts = 0;
         boolean guessedCorrectly = false;

         System.out.println("\nI have selected a number between 1 and " + maxNumber);
         System.out.println("You have " + maxAttempts + " attempts.");

         while (attempts < maxAttempts) {

             System.out.print("\nEnter your guess: ");
             int guess = sc.nextInt();

             attempts++;

             if (guess > randomNumber) {
                 System.out.println("Too High!");
             }
             else if (guess < randomNumber) {
                 System.out.println("Too Low!");
             }
             else {
                 System.out.println("Correct!");
                 guessedCorrectly = true;
                 break;
             }

             System.out.println("Attempts Used: " + attempts + "/" + maxAttempts);
         }
         if (guessedCorrectly) {
        	    System.out.println("You guessed the number in " + attempts + " attempts.");
        	} else {
        	    System.out.println("\nYou Lost!");
        	    System.out.println("The correct number was: " + randomNumber);
        	}
         if (guessedCorrectly) {
        	    scoreSummary += "Round " + round + " - Guessed in " + attempts + " attempts\n";
        	} else {
        	    scoreSummary += "Round " + round + " - Lost\n";
        	}
         System.out.println("\nRound " + round + " completed.");

         System.out.print("Do you want to play again? (Y/N): ");
         playAgain = sc.next().charAt(0);

         round++;

         } while (playAgain == 'Y' || playAgain == 'y');

         System.out.println("\n========== SCORE SUMMARY ==========");
         System.out.println(scoreSummary);

         System.out.println("Thanks for playing!");
         sc.close();


    }

}